# Generated by Django 3.1.6 on 2021-02-28 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='pun',
            new_name='punContent',
        ),
        migrations.RenameField(
            model_name='pun',
            old_name='content',
            new_name='punContent',
        ),
        migrations.RemoveField(
            model_name='call',
            name='title',
        ),
        migrations.AddField(
            model_name='call',
            name='deceasedName',
            field=models.CharField(default='sophie', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='source',
            field=models.URLField(blank=True, max_length=300, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
    ]
