# Generated by Django 3.1.6 on 2021-02-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlist', '0002_auto_20210228_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='dateOfDeath',
            field=models.CharField(default='20200101', max_length=200),
        ),
    ]
