# Generated by Django 3.1.6 on 2021-02-28 05:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deadlist', '0003_call_dateofdeath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='punContent',
        ),
        migrations.AddField(
            model_name='pun',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deadlist.call'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='callRating',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='call',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='call',
            name='dateOfDeath',
            field=models.CharField(default='01/01/2000', max_length=200),
        ),
    ]
